# Generated by Django 4.2.5 on 2023-09-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hour',
            name='id',
        ),
        migrations.AlterField(
            model_name='hour',
            name='cd_hour_minute',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
