# Generated by Django 4.2.5 on 2023-09-23 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_hour_id_alter_hour_cd_hour_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('module', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512, null=True)),
                ('module_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='self_module', to='core.module')),
            ],
            options={
                'db_table': 'module',
            },
        ),
    ]
