# Generated by Django 4.2.4 on 2023-09-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userlogin',
            table='user_login',
        ),
    ]
