# Generated by Django 4.2.5 on 2023-09-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0003_remove_user_username_user_id_user_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='user',
        ),
    ]
