# Generated by Django 4.2.5 on 2023-10-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_remove_license_owner_account'),
        ('user_login', '0005_userlogin_user_alter_user_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
