# Generated by Django 4.2.5 on 2023-10-01 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_remove_license_owner_account'),
        ('user_login', '0006_remove_userlogin_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('nm_first', models.CharField(max_length=50, null=True)),
                ('nm_last', models.CharField(max_length=50, null=True)),
                ('nm_complete', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('date_birth', models.DateField(null=True)),
                ('image', models.FileField(default='photo/no-photo.png', null=True, upload_to='photo/user')),
                ('sex_code', models.CharField(max_length=200, null=True)),
                ('sex_type', models.CharField(max_length=200, null=True)),
                ('occupation_code', models.CharField(max_length=200, null=True)),
                ('occupation_type', models.CharField(max_length=200, null=True)),
                ('licence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='license.license')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
