# Generated by Django 4.2.5 on 2023-09-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('group', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512, null=True)),
                ('order', models.IntegerField(null=True)),
                ('group_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='self_group', to='permission.group')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('permission', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512, null=True)),
                ('order', models.IntegerField(null=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_system', to='core.module')),
                ('permission_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='self_permission', to='permission.permission')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_permission', to='permission.group')),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permission_group', to='permission.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
