# Generated by Django 4.2.5 on 2023-09-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='system_group',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='system_permission',
        ),
        migrations.AlterModelTable(
            name='permissiongroup',
            table='system_permission_group_related',
        ),
    ]
