# Generated by Django 4.2.5 on 2023-10-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0008_userlogin_user'),
        ('permission', '0003_group_license_permission_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='principal_screen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PermissionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permission.permission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login.user')),
            ],
            options={
                'db_table': 'system_permission_user_related',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permission.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login.user')),
            ],
            options={
                'db_table': 'system_group_user_related',
            },
        ),
    ]
