# Generated by Django 4.2.5 on 2023-09-13 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'license_payment',
            },
        ),
        migrations.CreateModel(
            name='LicenseCategory',
            fields=[
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('type_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description_name', models.CharField(max_length=255, null=True)),
                ('time', models.IntegerField(null=True)),
                ('active', models.CharField(default=False)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='license.licensecategory')),
            ],
            options={
                'db_table': 'license_category',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('token', models.UUIDField()),
                ('activate_date', models.DateTimeField()),
                ('limit_date', models.DateTimeField()),
                ('active', models.CharField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='license.licensecategory')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='license.licensepayment')),
            ],
            options={
                'db_table': 'license',
            },
        ),
    ]
