# Generated by Django 4.2.5 on 2023-09-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseModule',
            fields=[
                ('dateCreated', models.DateTimeField(null=True)),
                ('dateModification', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('module', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512, null=True)),
                ('module_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='license.licensemodule')),
            ],
            options={
                'db_table': 'license_module',
            },
        ),
    ]
