# Generated by Django 4.2.5 on 2023-09-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_licensemodule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenseModule',
        ),
    ]
