# Generated by Django 4.2.5 on 2023-09-24 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_alter_user_table_alter_userlogin_table'),
        ('license', '0003_delete_licensemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='account_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='owner_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_owner', to='user_login.user'),
        ),
    ]
