# Generated by Django 4.2.5 on 2023-10-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_license_account_people_license_owner_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='owner_account',
        ),
    ]
