# Generated by Django 4.2.4 on 2023-09-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchat',
            name='type',
        ),
    ]
